=== wiskiw/PSU-IT_Labs_2016-2020/syard/LR6/test-schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wmh="http://www.wmhelp.com/2003/eGenerator" elementFormDefault="qualified">
  <xs:element name="LVData">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Version"/>
        <xs:element ref="Cluster" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Version" type="xs:string"/>
  <xs:element name="Cluster">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Name"/>
        <xs:element ref="NumElts"/>
        <xs:element ref="DBL" maxOccurs="unbounded"/>
        <xs:element ref="String" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Name">
    <xs:complexType/>
  </xs:element>
  <xs:element name="NumElts" type="xs:string"/>
  <xs:element name="DBL">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Name"/>
        <xs:element ref="Val"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Val" type="xs:string"/>
  <xs:element name="String">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Name"/>
        <xs:element ref="Val"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== wiskiw/PSU-IT_Labs_2016-2020/syard/LR6/data.xml
<?xml version="1.0" encoding="Windows-1251" standalone="no"?>
<LVData xsi:noNamespaceSchemaLocation="file:///C:/Users/Àíæåëèêà/Downloads/SYaRd/ÑßÐä/lab6/test-schema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<Version>16.0</Version>
<Cluster>
<Name/>
<NumElts>4</NumElts>
<DBL>
<Name/>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name/>
<Val>0.50000000000000</Val>
</DBL>
<String>
<Name/>
<Val>14.12.2018</Val>
</String>
<String>
<Name/>
<Val>09:23:12</Val>
</String>
</Cluster>
<Cluster>
<Name/>
<NumElts>4</NumElts>
<DBL>
<Name/>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name/>
<Val>0.50000000000000</Val>
</DBL>
<String>
<Name/>
<Val>14.12.2018</Val>
</String>
<String>
<Name/>
<Val>09:23:16</Val>
</String>
</Cluster>
<Cluster>
<Name/>
<NumElts>4</NumElts>
<DBL>
<Name/>
<Val>1.00000000000000</Val>
</DBL>
<DBL>
<Name/>
<Val>0.50000000000000</Val>
</DBL>
<String>
<Name/>
<Val>14.12.2018</Val>
</String>
<String>
<Name/>
<Val>09:23:22</Val>
</String>
</Cluster>
</LVData>
